# RIFERIMENTO PROTOCOLLO V_1.1
# INDIRIZZO REMOTO: http://13.42.233.112:8080/skillbuilders_1.0/
# INDIRIZZO LOCALE: http://localhost:8080/SkillBuilders_war/

### Verifica email (NON FUNZIONANTE)
POST http://localhost:8080/SkillBuilders_war/verificaEmail
Content-Type: application/json

{
  "email": "nicola1.travaglini@gmail.com"
}

### Controlla Otp email (NON FUNZIONANTE)
POST http://localhost:8080/SkillBuilders_war/controllaOtpEmail
Content-Type: application/json

{
  "otp": 74206
}

### Registrazione
POST http://localhost:8080/SkillBuilders_war/registrazione
Content-Type: application/json

{
  "nome": "trava",
  "password": "ciao",
  "email": "nicola1.travaglini@gmail.com",
  "anno": 5,
  "indirizzo": "informatico",
  "foto": "ciao.jpg",
  "comune": "Navile",
  "flagTutor": true
}

### Registrazione
POST http://13.42.233.112:8080/skillbuilders_1.0/registrazione
Content-Type: application/json

{
  "nome": "Francesco",
  "password": "specifichebrutte",
  "email": "sorghi@gmail.com",
  "anno": 3,
  "indirizzo": "informatico",
  "foto": "ciao.jpg",
  "comune": "Navile",
  "flagTutor": false
}

### Accesso
POST http://13.42.233.112:8080/skillbuilders_1.0/accesso
Content-Type: application/json

{
  "email": "sorghi@gmail.com",
  "password": "specifichebrutte"
}

### Visualizza proprio
POST http://13.42.233.112:8080/skillbuilders_1.0/visualizzaProprio
Content-Type: application/json

{
}

### Visualizza altrui
POST http://13.42.233.112:8080/skillbuilders_1.0/visualizzaAltrui
Content-Type: application/json

{
}

### Visualizza ticket
POST http://13.42.233.112:8080/skillbuilders_1.0/visualizzaTicket
Content-Type: application/json

{
  "anno": 3,
  "provincia": "bolognetta",
  "materia": "informatica"
}

### Cambia flag
POST http://13.42.233.112:8080/skillbuilders_1.0/cambiaFlag
Content-Type: application/json

{
  "flagTutor": true
}

### Visualizza tutor
POST http://13.42.233.112:8080/skillbuilders_1.0/visualizzaTutor
Content-Type: application/json

{
  "anno": 3,
  "provincia": "bolognetta",
  "indirizzo": "informatica"
}