POST http://13.42.233.112:8080/skillbuilders_1.0/registrazione
Content-Type: application/json

{
"nome": "Francesco",
"password": "specifichebrutte",
"email": "sorghi@gmail.com",
"anno": 3,
"indirizzo": "informatico",
"sezione": "B",
"quartiere": "Navile"
}

###
POST http://13.42.233.112:8080/skillbuilders_1.0/accesso
Content-Type: application/json

{
"email": "sorghi@gmail.com",
"password": "specifichebrutte"
}
