# RIFERIMENTO PROTOCOLLO V_1.1
# INDIRIZZO REMOTO: http://13.42.233.112:8080/skillbuilders_1.0/
# INDIRIZZO LOCALE: http://localhost:8080/SkillBuilders_war/

### Verifica email
POST http://13.42.233.112:8080/skillbuilders_1.0/verificaEmail
Content-Type: application/json

{
  "email": "nicola1.travaglini@gmail.com"
}

### Controlla Otp email
POST http://13.42.233.112:8080/skillbuilders_1.0/controllaOtpEmail
Content-Type: application/json

{
  "otp": 53924
}

### Registrazione
POST http://localhost:8080/SkillBuilders_war/registrazione
Content-Type: application/json

{
  "nome": "sos",
  "password": "ciao",
  "email": "travaglini@gmail.com",
  "anno": 5,
  "indirizzo": "grafico",
  "foto": "ciao.jpg",
  "comune": "Bolognina",
  "flagTutor": true
}

### Accesso
POST http://localhost:8080/SkillBuilders_war/accesso
Content-Type: application/json

{
  "email": "travaglini@gmail.com",
  "password": "ciao"
}

### Logout (DA TESTARE)
GET http://localhost:8080/SkillBuilders_war/logout
Content-Type: application/json

{
}

### Visualizza proprio
POST http://localhost:8080/SkillBuilders_war/visualizzaProprio
Content-Type: application/json

{
}

### Visualizza altrui
POST http://13.42.233.112:8080/skillbuilders_1.0/visualizzaAltrui
Content-Type: application/json

{
}

### Visualizza tickets
POST http://13.42.233.112:8080/skillbuilders_1.0/visualizzaTickets
Content-Type: application/json

{
  "anno": 0,
  "comune": "",
  "materia": ""
}

### Visualizza ticket
POST http://localhost:8080/SkillBuilders_war/visualizzaTicket
Content-Type: application/json

{
  "id": 3
}

### Visualizza tutors
POST http://localhost:8080/SkillBuilders_war/visualizzaTutors
Content-Type: application/json

{
  "anno": 0,
  "comune": "",
  "indirizzo": ""
}

### Inserisci ticket
POST http://localhost:8080/SkillBuilders_war/inserisciTicket
Content-Type: application/json

{
  "testo": "Aiuto psicologico per amore",
  "materia": "sostegno"
}

### Inserisci recensione (DA TESTARE)
POST http://localhost:8080/SkillBuilders_war/nuovaRecensione
Content-Type: application/json

{
  "voto": 5,
  "descrizione": "che schif",
  "materia": "informatica",
  "email_tutor": "sorghi@gmail.com"
}

### Cambia flag
POST http://13.42.233.112:8080/skillbuilders_1.0/cambiaFlag
Content-Type: application/json

{
  "flagTutor": true
}

### Modifica recensione (DA TESTARE)
POST http://localhost:8080/SkillBuilders_war/modificaRecensione
Content-Type: application/json

{
  "id": 1,
  "voto": 10,
  "descrizione": "che bella!",
  "materia": "informatica",
  "email_tutor": "sorghi@gmail.com"
}

### Elimina utente (DA TESTARE)
GET http://localhost:8080/SkillBuilders_war/eliminazione
Content-Type: application/json

{
}